### ISSUE TITLE
When continuing from the history, it would be great to be able to navigate episodes back and forward

### ISSUE THREAD

**Issue by 097115** [justchokingaround/lobster#1]
As of now, if we run `lobster -c` and then select an entry from the history, `lobster` will open the next episode relatively to the one that is stored in history. E.g., if we have *Family Guy: S19 Ep(4)*, it will play *Family Guy: S19 Ep(5)*. But what if we haven't actually finished watching this last episode from the history? Just opened it and then closed for some reasons? And now would like to re-watch it?

To replay the last episode, or to skip the next one, my quick and dirty solution was to introduce the following bindings to the `fzf` selector:

    selection=$(fzf -1 --cycle --bind='f1:execute(printf "decr")+accept' --bind='f2:execute(printf "incr")+accept' --with-nth 4.. < "$history_file")
      [ -z "$selection" ] && exit 0
      case "$selection" in
        decr*)
          selection=$(echo "$selection" | sed 's/^decr//' | sed -r 's/(.*)(Ep\()([0-9]+)(.*)/echo "\1\2$((\3-1))\4"/ge')
          ;;
        incr*)
          selection=$(echo "$selection" | sed 's/^incr//' | sed -r 's/(.*)(Ep\()([0-9]+)(.*)/echo "\1\2$((\3+1))\4"/ge')
          ;;
      esac

But may be there are some better ways? And what do you think of such possibility in general?

**Comment by justchokingaround** [comment]
although the idea of introducing fzf keybinds does sound interesting, and i would gladly integrate it into the script, i don't really see the point for this use case. as the script is supposed to function, after finishing an episode, the user is prompted to mark the episode as completed, or exit. so right now, if the user doesn't press `Enter` after he finished watching an episode, the play_from_history function will pick up from the same episode next time he uses `-c`. i should probably document this, so that it's more clear. if this issue will however really be needed, i think implementing a menu after an episode has finished playing would probably make more sense, and would be more user-friendly. or maybe i'll add an argument to directly edit the history file
 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/44473782/180923515-442cdd77-904f-4af6-a21d-f0edc863f3a9.png">

**Comment by 097115** [comment]
> the user is prompted to mark the episode as completed, or exit

It doesn't prompt me if I exit the player myself, though (and adds the episode automatically)? Or is it something with my config?

Like, I run `lobster`, select a show / season / episode, it starts playing, I quit `mpv` by pressing `q`, and this "aborted" episode is automatically saved to the history file.

**Comment by justchokingaround** [comment]
oh... what OS are u using? i'll look into it

**Comment by 097115** [comment]
Ubuntu 21.10, `/bin/sh` is symlinked to `dash` version 0.5.11.

After quitting the player, it says

    Press Enter to mark episode as watched or Ctrl-C to exit
    lobster.sh: 81: read: arg count

Somehow missed this before...

**Comment by justchokingaround** [comment]
so does this mean it works as intended?

**Comment by 097115** [comment]
Well, obviously not:

> `lobster.sh: 81: read: arg count`

Seems like `dash`'s `read` wants a variable there :)

**Comment by justchokingaround** [comment]
this is indeed a dash issue. i was able to reproduce it. and since a lot of (smart) people symlink /bin/sh to dash, i'll push a fix asap, ty for letting me know

**Comment by justchokingaround** [comment]
latest commit should've fixed it, could you please check on ur side when u get time and consider closing the issue if it did?

**Comment by 097115** [comment]
Yeah, this seems to be working :)

The original suggestion still stands, though: it would be great to have an ability to navigate between episodes (except the solution I proposed initially obviously doesn't work). But may be something will eventually come to you? Would be great to know :)

**Comment by justchokingaround** [comment]
i'll think about it. if more people will want this feature, i'll implement a menu between episodes
