### ISSUE TITLE
[bug] search order changes with ueberzugpp

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#105]
**Describe the bug**

Under ueberzugpp the results are by alphabetical order. Under normal fzf, it seams they are ordered by relevance. Maybe there's the same problem with rofi and images but didn't test.

**To Reproduce**

just try with `lobster star trek`.

**Expected behavior**
The order should be the same.

**Comment by justchokingaround** [comment]
the problem with this is that the images are downloaded asynchronously, by sending the the curl process in the background:
```sh
  download_thumbnails() {
    printf "%s\n" "$1" | while read -r cover_url id type title; do
      curl -s -o "$images_cache_dir/  $title ($type)  $id.jpg" "$cover_url" &
      if [ "$use_external_menu" = "1" ]; then
        entry=/tmp/lobster/applications/"$id.desktop"
        generate_desktop "$title ($type)" "$images_cache_dir/  $title ($type)  $id.jpg" >"$entry" &
      fi
    done
    wait && sleep "$2"
  }
```
line `curl -s -o "$images_cache_dir/  $title ($type)  $id.jpg" "$cover_url" &`

even if i add the `-tr` flags to the `ls` command used in the `image_preview_fzf` function, 
```sh
choice=$(ls -tr "$images_cache_dir"/* | fzf -i -q "$1" --preview='ueberzugpp cmd -s $SOCKET -i fzfpreview -a add -x $X -y $Y --max-width $FZF_PREVIEW_COLUMNS --max-height $FZF_PREVIEW_LINES -f {}' --reverse --with-nth 2 -d "  " --preview-window=30%)
```
it will not work properly since the order of downloading is random.

i am closing this issue as not planned for the time being, since i don't think this is too important, but if another person complaints about this or opens another issue, i will look into an implementation that will fix this problem
