### ISSUE TITLE
No link found eventhough you can play in the website.

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#11]
![1](https://user-images.githubusercontent.com/95531944/183287520-b10c0724-c527-4bad-b672-9c295f9400b5.png)
![2](https://user-images.githubusercontent.com/95531944/183287526-0756f25d-080d-4d40-ae1c-e3a33c26fe0b.png)

**Comment by justchokingaround** [comment]
fixed in https://github.com/justchokingaround/lobster/commit/61dd80b0cb2fd4895e023a415e2463ce4e588747

pls check if it works for you (to update `sudo lobster -u`)

also quick tip, you can start typing during selection, for instance, you'd search for the movie `spider-man` and then in the selection menu you can just type `no way` and it'll filter automatically

**Comment by ttx99** [comment]
![Screenshot_2022-08-07_19-12-52](https://user-images.githubusercontent.com/95531944/183287898-b4c84e75-b62f-4aba-b652-c931ef51e67f.png)

**Comment by justchokingaround** [comment]
you'll have to install patch then, i'll add it to the dependency list, usually it comes preinstalled on most distros

**Comment by ttx99** [comment]
what patch? and how?

**Comment by justchokingaround** [comment]
patch is a tool what distro/OS are u using?

**Comment by ttx99** [comment]
Sorry, its working now had to reinstall
![Screenshot_2022-08-07_19-12-52](https://user-images.githubusercontent.com/95531944/183288195-f993836e-231e-4ff4-bd56-6bde353295dd.png)

**Comment by justchokingaround** [comment]
installing `patch` will make it easier to update in the future 🙏
