### ISSUE TITLE
uebergzugpp not working

### ISSUE THREAD

**Issue by ttx99** [justchokingaround/lobster#142]
uebergzugpp not working
![Screenshot_2023-07-14_10-32-53](https://github.com/justchokingaround/lobster/assets/95531944/cd4b4a85-9cfb-4aff-80f7-266cff4917bb)

**Comment by justchokingaround** [comment]
my `ueberzugpp` currently doesn't work for me, i've opened an issue upstream (https://github.com/jstkdng/ueberzugpp/issues/89), so i'm not really sure if i can do much about it. regardless this seems more like an issue with ueberzugpp rather than the script, especially when considering that i have made no changes to anything with regards to ueberzugpp inside of lobster in the past ~2 weeks. please send me the logs regardless, i'll see what can be done

**Comment by jstkdng** [comment]
hey, you just need to recompile `ueberzugpp` as there was an opencv update recently.

**Comment by ttx99** [comment]
@jstkdng 
thanks fixed now
