### ISSUE TITLE
download multiple files (eg. complete season)

### ISSUE THREAD

**Issue by ek234** [justchokingaround/lobster#149]
**Is your feature request related to a problem? Please describe.**
it would be convenient to be able to download a complete season of a tv show in one go.

**Describe the solution you'd like**
adding an option to select the whole season/ multiple episodes which are then downloaded sequentially or parallelly.

**Describe alternatives you've considered**
writing an external script that runs lobster with the download flag for each episode.

**Additional context**
really nice program, thanks! anyway, I can add this feature if you temme if and how you would like it to be implemented.

**Comment by justchokingaround** [comment]
it would be really nice if you could PR this! since i'm busy with exams in the next 2 weeks.

what i think would be a nice implementation for this feature:
* `-b` and `--batch` as arguments with a range that can be given using any separator: `a:b` or `a-b` where u match a number then any symbol and then any number again. using regex it would look something like this: `[0-9]*.[0-9]*`
* then you make a for loop to fetch and download each video link individually, using the `next_episode_exists` function to check for the existence of a next episode

the rest is up to you tbh, i don't have any particular requirements for it.

this might not be the easiest thing to implement so don't push yourself too hard. i am planning on starting a complete rewrite of the project in rust in ~1.5 week, and i will implement this feature then, so there might not even be a need for you to go out of your way for this

**Comment by ek234** [comment]
@justchokingaround cool. rust rewrite sounds fun. maybe I can help with that. atb for your exams!

**Comment by justchokingaround** [comment]
thanks!

**Comment by ek234** [comment]
@justchokingaround  hey man. did you start working on the rust rewrite? just got a little free i can contribute.

**Comment by justchokingaround** [comment]
yes, i'll add you to the repo. also it'd be nice if u join the discord server, we do a lot of organizational talk there

**Comment by justchokingaround** [comment]
out of scope for the shell project
