### ISSUE TITLE
Fun Fact: This kinda works perfectly on Android!

### ISSUE THREAD

**Issue by THEGOLDENPRO** [justchokingaround/lobster#164]
I'm aware Android support is out of this project's scope but for those who desperately want lobster in Termux you're actually a config line away.

### How to enable it:

```sh
nano ~/.config/lobster/lobster_config.txt
```
(you can use ``lobster -e`` if you know how to ~~escape vim~~ or you've already set it to nano like me 😭)

Then once you're in the config set player to this monstrosity of a line.
```
player="am start -n is.xyz.mpv/is.xyz.mpv.MPVActivity -e filepath"
```

Thanks to lobster 🦞 allowing custom players this is possible using the MPV termux intent. 🙏

Anyways hope you have a good rest of your day, good bye.

**Comment by justchokingaround** [comment]
just as a disclaimer: if anyone is willing to PR/maintain android mpv support, i am willing to merge those changes, i just won't be maintaining it myself

**Comment by SheeperGit** [comment]
Hey @THEGOLDENPRO!

Thanks for detailing the steps on how to get lobster working in termux.
I myself have been trying to get it to work, but I think I've failed because I've installed it from the wrong source (e.g., Arch, Debian, NixOS, Mac, Windows, etc.)

When trying to install the software using the `Linux (from source)` steps:
`sudo curl -sL github.com/justchokingaround/lobster/raw/main/lobster.sh -o /usr/local/bin/lobster &&
sudo chmod +x /usr/local/bin/lobster`

the `lobster.sh` script gave errors. Naturally, the `lobster` command was also not added to my $PATH, so I think I've picked the wrong source to install it from.

I'd love it if you could tell me what you believe I've done wrong, and perhaps even detail your steps of the installation of `lobster` on `termux`, if you believe it necessary.

Thanks in advance, my friend! Enjoy your movies!

**Comment by justchokingaround** [comment]
https://github.com/justchokingaround/lobster/pull/219

**Comment by SheeperGit** [comment]
Thanks for the quick reply, justchokingaround!

I saw your previous reply in another issue https://github.com/justchokingaround/lobster/pull/219#issuecomment-2295729987
i'm indeed experiencing the same problem with the /tmp directory unable to be created due to it being a read-only filesystem. After replacing all occurrences of `/tmp` with the environment variable`$TMPDIR`, the script does indeed work.

Thanks a bunch for your help, my friend!

**Comment by yeartwothousandfive** [comment]
can anyone help me what's the step by step tutorial on how to work this on termux? the description on read.md is quite vague. 😭😭
