### ISSUE TITLE
[feat]: new provider -> fmovies

### ISSUE THREAD

**Issue by stunner999** [justchokingaround/lobster#176]
uhm, https://fmoviesz.to/ pls... merry xmas

**Comment by pitsi** [comment]
May I explain why this is a lot of work?

Fmovies is not a provider, it is a whole different site, similar to the one lobster scrapes now. This means that a new shell script has to be created, let's name it... "crab", which would scrape from it. After that, because fmovies uses different providers (= the links that play the embedded videos), new functions must be made for those providers, and they have to be specific for crab.

So yea, it is almost like a complete rewrite of the whole script :(
