### ISSUE TITLE
Feature request: download option?

### ISSUE THREAD

**Issue by ehewins** [justchokingaround/lobster#3]
Hey there, first of all thanks for sharing this really cool script. I was wondering if it would be possible to add a flag/option which downloads a given video rather than streaming it? I've had a little play around with the script myself but when I tried downloading $mpv_link using aria2c it gave me some sort of playlist rather than a video file, at which point I ran out of ideas (I don't really have any experience with web scraping).
Thanks, and I hope this is the right way of asking about it (I'm also pretty new to github as well)

**Comment by justchokingaround** [comment]
this the right way of asking about it, so no worries on that side of things.
1. these are m3u8 links, and not mp4 links, therefore simply using aria2c won't work. here's a script you can use to download m3u8 links: https://github.com/CoolnsX/hls_downloader
if you have any questions or trouble regarding this script, the fastest way would be to ask coolansx or me on the ani-cli discord server (you don't have to ofc, it would just be the fastest way)
2. i'm not very fond of adding a downloading feature, due to the disclaimer on himovie's website:
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/44473782/181612466-27cef609-4a73-42b2-a42c-e9d8cbe12b05.png">
i personally don't think it would be that problematic if someone would do that, especially if you use a vpn/proxy, but i don't really want to add this feature to the mainstream script
