### ISSUE TITLE
lobster -e

### ISSUE THREAD

**Issue by pirate486743186** [justchokingaround/lobster#97]
that was a nice little feature.

**Comment by justchokingaround** [comment]
the problem is that `-x`, `--debug` takes priority over it, and given how `stderr` is redirected to `stdout` and tee is used to store that in a log file, `-e` cannot be supported, if the editor is a terminal text editor, and i don't want to implement it for only gui editors, because it would kind of lose its point

**Comment by justchokingaround** [comment]
found a workaround, and brought this option back in 75ce98b031055efca4f5a296b6ab698e07cc5dc2 @pirate486743186
